### PR TITLE
Vendor gitlab bindings fix for DiffNote.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Fix for https://github.com/MagnusS/okra/issues/101

Could you try this fix out @samoht ?
Unfortunately the API docs aren't comprehensive on some responses.

### CODE REVIEW

**Comment by samoht** [comment]
That works thanks!

**Comment by MagnusS** [comment]
I merged #103 so this should build with a rebase

**Comment by TheLortex** [comment]
Hi, I am getting the following error using this PR (rebased on `main`):

```
okra: internal error, uncaught exception:
      (Failure
         "Bad response: Atdgen_runtime.Oj_run.Error(\"Line 1:\\nUnsupported variant \\\"DiscussionNote\\\"\")\
```

**Comment by tmcgilchrist** [comment]
Noticed this too, working on a fix.

**Comment by tmcgilchrist** [comment]
@TheLortex Could you try this fix?

**Comment by tmcgilchrist** [comment]
Fixes included in gitlab.0.1.4 as part of https://github.com/MagnusS/okra/pull/107

**Pull request closed without merging**
