### PR TITLE
add basic gitlab support

### PR DESCRIPTION
**Pull request by patricoferris**
This PR adds basic Gitlab support (it's a draft as I need to upstream some changes to `ocaml-gitlab`). It only integrates Merge Requests and Issues at the moment. I have a feeling it might be a little verbose and add an activity for every event like commenting on an issue, so I will test that too. For now it is enough to have an okra conf like:

```yaml
gitlab_token: <READ-USER-TOKEN>
```

And `okra generate` will add activities like:

```markdown
  - PR (Gitlab): "opened" update readme https://gitlab.com/patrickferris/ocaml-sctp/-/merge_requests/1
  - PR (Gitlab): "accepted" update readme https://gitlab.com/patrickferris/ocaml-sctp/-/merge_requests/1
  - Issue (Gitlab): The protocol needs to be implemented https://gitlab.com/patrickferris/ocaml-sctp/-/issues/1
```

Not sure what the best formatting is so happy to hear suggestions on that too.

### CODE REVIEW

**Comment by patricoferris** [comment]
With the changes in `ocaml-gitlab` (thanks Tim!) I think this is ready for a review, it would be good I think to get some frequent Gitlab users to take it for a spin perhaps?

**Comment by MagnusS** [comment]
@craigfe you mentioned you were going to test this for the next weekly, did it work ok?

**Comment by patricoferris** [comment]
(No rush on testing!!), Gitlab was released today so to try it you may need an `opam update` before installing :))

**Comment by tmcgilchrist** [comment]
@MagnusS This has been working fine for me. 🦖 

@patricoferris I added the query parameters to events, the code could use that directly now. https://github.com/tmcgilchrist/okra/commit/214efc0f2fceb8cc9949fa84dd0e25147e6ccb96

**Comment by patricoferris** [comment]
Thanks @tmcgilchrist 👍

**Comment by MagnusS** [comment]
Thanks!

**Comment by MagnusS** [comment]
It would be useful with a README update on how to use this! But merging this PR as is :)

**Comment by samoht** [comment]
I've got:

```
         "Bad response: Atdgen_runtime.Oj_run.Error(\"Line 1:\\nUnsupported variant \\\"DiffNote\\\"\")\
```

**Comment by tmcgilchrist** [comment]
@samoht could you rerun okra with `GITLAB_DEBUG=1` and share the offending json response?

**Comment by samoht** [comment]
@tmcgilchrist I've opened https://github.com/MagnusS/okra/issues/101

**Pull request merged**
