### PR TITLE
initial repository reporting feature

### PR DESCRIPTION
**Pull request by patricoferris**
This is more of a draft PR with the initial `okra monthly <repos> --month=<X> --year=<Y>` command. This pulls in the the PRs and issues from the specified month and year for each of the projects. I'm still not exactly sure of the semantics we want for inclusion, right now (if I coded it properly) we have:

 - PRs: these are the PRs that were opened in that month, if they were also merged within the month then they are shifted into that category. We might want "all PRs merged in the month" which would mean changing the query.
 - Issues: these are the issues opened in the month

A lot of logic goes into getting the PRs because the Github graphql API only lets you get 100 results and then you have to paginate your way backwards (or forwards) unless I missed something.

## Example 

Below is the raw output of doing `okra monthly mirage/irmin`, there's room for improvement with the times, layout, ordering perhaps but it should give a good idea. I also need to do more testing to make sure it is the correct set of items! I also removed the @ to not ping everybody!

------

# Reports (2021-09-01T00:00:00Z - 2021-10-01T00:00:00Z)

# irmin
Irmin is a distributed database that follows the same design principles as Git

### Opened (and not merged in same time frame)

 - [[WIP] irmin-pack: add a direct-addressing mode for internal pointers](https://github.com/mirage/irmin/pull/1534) by <AT>CraigFe

   (created: 2021-09-26T20:56:13Z)

 - [Attach source code locations to Irmin's log lines](https://github.com/mirage/irmin/pull/1533) by <AT>CraigFe

   (created: 2021-09-26T20:50:23Z, reviewed by: <AT>CraigFe)

 - [Fix fold in the case the update map is not empty](https://github.com/mirage/irmin/pull/1532) by <AT>icristescu

   (created: 2021-09-24T09:25:48Z, reviewed by: <AT>CraigFe, <AT>Ngoguey42, <AT>icristescu)

 - [Fix fold for update maps](https://github.com/mirage/irmin/pull/1531) by <AT>icristescu

   (created: 2021-09-24T08:06:00Z)

 - [irmin: remove cache for tree values](https://github.com/mirage/irmin/pull/1524) by <AT>samoht

   (created: 2021-09-09T16:43:16Z)

 - [irmin: use a tail-rec version of List.of_seq](https://github.com/mirage/irmin/pull/1514) by <AT>samoht

   (created: 2021-09-06T13:10:41Z, reviewed by: <AT>Ngoguey42, <AT>samoht)
### Merged

 - [irmin-pack: fix typo in name of the `irmin-test` suite](https://github.com/mirage/irmin/pull/1535) by <AT>CraigFe

   (merged: 2021-09-27T16:13:43Z, reviewed by: <AT>Ngoguey42, <AT>icristescu)

 - [irmin: rename `Store.Private` to `Store.Backend`](https://github.com/mirage/irmin/pull/1530) by <AT>CraigFe

   (merged: 2021-09-21T09:03:21Z, reviewed by: <AT>Ngoguey42)

 - [Use a `tree` parameter in `fold` ](https://github.com/mirage/irmin/pull/1527) by <AT>icristescu

   (merged: 2021-09-16T13:38:52Z, reviewed by: <AT>Ngoguey42, <AT>icristescu, <AT>samoht)

 - [Rework caching](https://github.com/mirage/irmin/pull/1526) by <AT>Ngoguey42

   (merged: 2021-09-20T12:52:16Z, reviewed by: <AT>CraigFe, <AT>Ngoguey42, <AT>icristescu, <AT>samoht)

 - [Use seq in Tree.fold](https://github.com/mirage/irmin/pull/1525) by <AT>icristescu

   (merged: 2021-09-16T11:53:23Z, reviewed by: <AT>CraigFe, <AT>Ngoguey42, <AT>icristescu, <AT>samoht)

 - [irmin-mirage: Add missing constraint on Irmin_mirage_git.KV_maker](https://github.com/mirage/irmin/pull/1521) by <AT>Ngoguey42

   (merged: 2021-09-09T09:41:52Z)

 - [irmin: compare lazy nodes and contents by hash](https://github.com/mirage/irmin/pull/1519) by <AT>CraigFe

   (merged: 2021-09-07T06:57:43Z, reviewed by: <AT>Ngoguey42, <AT>samoht)

 - [Avoid implicit use of polymorphic equality via `List.mem`](https://github.com/mirage/irmin/pull/1518) by <AT>CraigFe

   (merged: 2021-09-07T08:22:05Z, reviewed by: <AT>Ngoguey42, <AT>icristescu)

 - [irmin-git: temporary disable the package on s390x](https://github.com/mirage/irmin/pull/1516) by <AT>samoht

   (merged: 2021-09-06T21:10:13Z, reviewed by: <AT>CraigFe)

 - [irmin: better clear](https://github.com/mirage/irmin/pull/1515) by <AT>samoht

   (merged: 2021-09-06T15:03:08Z, reviewed by: <AT>CraigFe, <AT>icristescu)

 - [irmin-test: make the core suite type abstract](https://github.com/mirage/irmin/pull/1513) by <AT>CraigFe

   (merged: 2021-09-06T14:11:00Z, reviewed by: <AT>Ngoguey42)

 - [Use the latest version of Repr](https://github.com/mirage/irmin/pull/1512) by <AT>CraigFe

   (merged: 2021-09-03T13:06:59Z, reviewed by: <AT>Ngoguey42)

 - [irmin-pack: avoid assuming the encoding of atomic write keys](https://github.com/mirage/irmin/pull/1511) by <AT>CraigFe

   (merged: 2021-09-03T13:07:51Z, reviewed by: <AT>icristescu)

 - [Add support for non-content-addressed backends](https://github.com/mirage/irmin/pull/1510) by <AT>CraigFe

   (merged: 2021-09-20T16:29:45Z, reviewed by: <AT>CraigFe, <AT>Ngoguey42, <AT>icristescu, <AT>samoht)

 - [New tree export](https://github.com/mirage/irmin/pull/1508) by <AT>Ngoguey42

   (merged: 2021-09-10T12:03:36Z, reviewed by: <AT>CraigFe, <AT>Ngoguey42, <AT>icristescu, <AT>samoht)

## Issues

- [Avoid use of polymorphic equality in `irmin/commit.ml`](https://github.com/mirage/irmin/issues/1517) by <AT>CraigFe

   (created: 2021-09-06T21:31:14Z)

- [flaky tests in irmin-http](https://github.com/mirage/irmin/issues/1520) by <AT>Ngoguey42

   (created: 2021-09-07T09:05:55Z)

- [iteration improvements in tree](https://github.com/mirage/irmin/issues/1522) by <AT>Ngoguey42

   (created: 2021-09-08T16:15:09Z)

- [Get access to the path in content merge function](https://github.com/mirage/irmin/issues/1523) by <AT>clecat

   (created: 2021-09-09T10:06:48Z)

- [Avoid global mutable state for stat-tracking in `tree.ml`](https://github.com/mirage/irmin/issues/1528) by <AT>CraigFe

   (created: 2021-09-20T13:09:18Z)

- [Rename `Store.Private` to `Store.Backend`](https://github.com/mirage/irmin/issues/1529) by <AT>CraigFe

   (created: 2021-09-20T14:19:45Z)

### CODE REVIEW

**Comment by patricoferris** [comment]
And..... I forget that Github adds a "this PR mentioned you" if you use the link!! Sorry Irmin-devs 🤦 ...

**Comment by MagnusS** [comment]
This looks great! Instead of having its own subcommand tied to the time interval, perhaps it could be integrated with `okra generate` as a different report type?

**Comment by MagnusS** [comment]
Perhaps we could call this new report repository report instead, as it pulls activity related to one or more repositories. `okra generate` could then support `--engineer` and `--repository=[...]` and default to `--engineer`. I guess the time selection will be slightly different though, unless we could allow `--week=[x,y,z]`, `--month=` and `--year` for both

**Comment by patricoferris** [comment]
This should be ready now, to summarise the recent changes:

 - Time is now handled as a range with the ability to ask for a single `week`, a range `weeks`, a single `month` and an optional year for all of them. Until the feature request comes in for a list of separate weeks I don't think we need to add it (it would just have to be same ranges logic + multiple requests anyway given the graphql API). These time frame options apply to both engineer reports and repository reports.
 - Repository reports can be generated using `okra generate --repositories=X` here `X` is a comma-separated list of `owner/repo`s. The default is to be an engineer report.
 
As I've mentioned a few times (and left a comment in the code about it) we have to paginate backwards in time for repositories (there's no `from` and `to` like get-activity afaict) which isn't as efficient particularly for repositories that encounter a lot of PRs/issues (I wouldn't recommend going too far back in time for `opam-repository` for example 😬 )

**Comment by MagnusS** [comment]
I think this is a good start; maybe we can improve the api calls later. I guess we can't really parse this report yet so it won't be part of the okr workflow, but it's nice to have available.

LGTM, but needs a rebase

**Comment by MagnusS** [comment]
Thanks!

**Pull request merged**
